// generated by go run gen.go; DO NOT EDIT

// +build !appengine
// +build gc
// +build !noasm

#include "textflag.h"

// fl is short for floating point math. fx is short for fixed point math.

DATA flAlmost65536<>+0x00(SB)/8, $0x477fffff477fffff
DATA flAlmost65536<>+0x08(SB)/8, $0x477fffff477fffff
DATA flOne<>+0x00(SB)/8, $0x3f8000003f800000
DATA flOne<>+0x08(SB)/8, $0x3f8000003f800000
DATA flSignMask<>+0x00(SB)/8, $0x7fffffff7fffffff
DATA flSignMask<>+0x08(SB)/8, $0x7fffffff7fffffff

// scatterAndMulBy0x101 is a PSHUFB mask that brings the low four bytes of an
// XMM register to the low byte of that register's four uint32 values. It
// duplicates those bytes, effectively multiplying each uint32 by 0x101.
//
// It transforms a little-endian 16-byte XMM value from
//	ijkl????????????
// to
//	ii00jj00kk00ll00
DATA scatterAndMulBy0x101<>+0x00(SB)/8, $0x8080010180800000
DATA scatterAndMulBy0x101<>+0x08(SB)/8, $0x8080030380800202

// gather is a PSHUFB mask that brings the second-lowest byte of the XMM
// register's four uint32 values to the low four bytes of that register.
//
// It transforms a little-endian 16-byte XMM value from
//	?i???j???k???l??
// to
//	ijkl000000000000
DATA gather<>+0x00(SB)/8, $0x808080800d090501
DATA gather<>+0x08(SB)/8, $0x8080808080808080

DATA fxAlmost65536<>+0x00(SB)/8, $0x0000ffff0000ffff
DATA fxAlmost65536<>+0x08(SB)/8, $0x0000ffff0000ffff
DATA inverseFFFF<>+0x00(SB)/8, $0x8000800180008001
DATA inverseFFFF<>+0x08(SB)/8, $0x8000800180008001

GLOBL flAlmost65536<>(SB), (NOPTR+RODATA), $16
GLOBL flOne<>(SB), (NOPTR+RODATA), $16
GLOBL flSignMask<>(SB), (NOPTR+RODATA), $16
GLOBL scatterAndMulBy0x101<>(SB), (NOPTR+RODATA), $16
GLOBL gather<>(SB), (NOPTR+RODATA), $16
GLOBL fxAlmost65536<>(SB), (NOPTR+RODATA), $16
GLOBL inverseFFFF<>(SB), (NOPTR+RODATA), $16

// func haveSSE4_1() bool
TEXT ·haveSSE4_1(SB), NOSPLIT, $0
	MOVQ $1, AX
	CPUID
	SHRQ $19, CX
	ANDQ $1, CX
	MOVB CX, ret+0(FP)
	RET

// ----------------------------------------------------------------------------

// func fixedAccumulateOpOverSIMD(dst []uint8, src []uint32)
//
// XMM registers. Variable names are per
// https://github.com/google/font-rs/blob/master/src/accumulate.c
//
//	xmm0	scratch
//	xmm1	x
//	xmm2	y, z
//	xmm3	-
//	xmm4	-
//	xmm5	fxAlmost65536
//	xmm6	gather
//	xmm7	offset
//	xmm8	scatterAndMulBy0x101
//	xmm9	fxAlmost65536
//	xmm10	inverseFFFF
TEXT ·fixedAccumulateOpOverSIMD(SB), NOSPLIT, $0-48

	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), BX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), R10

	// Sanity check that len(dst) >= len(src).
	CMPQ BX, R10
	JLT  fxAccOpOverEnd

	// R10 = len(src) &^ 8 (for Loop8)
	// R11 = len(src)
	// R12 = len(src) &^ 4 (for Loop4 fallback)
	MOVQ R10, R11
	MOVQ R10, R12
	ANDQ $-8, R10
	ANDQ $-4, R12

	// fxAlmost65536 := XMM(0x0000ffff repeated four times) // Maximum of an uint16.
	MOVOU fxAlmost65536<>(SB), X5

	// gather               := XMM(see above)                      // PSHUFB shuffle mask.
	// scatterAndMulBy0x101 := XMM(see above)                      // PSHUFB shuffle mask.
	// fxAlmost65536        := XMM(0x0000ffff repeated four times) // 0xffff.
	// inverseFFFF          := XMM(0x80008001 repeated four times) // Magic constant for dividing by 0xffff.
	MOVOU gather<>(SB), X6
	MOVOU scatterAndMulBy0x101<>(SB), X8
	MOVOU fxAlmost65536<>(SB), X9
	MOVOU inverseFFFF<>(SB), X10

	// offset := XMM(0x00000000 repeated four times) // Cumulative sum.
	XORPS X7, X7

	// i := 0
	MOVQ $0, R9

fxAccOpOverLoop8:
	// for i < (len(src) &^ 8)
	CMPQ R9, R10
	JAE  fxAccOpOverLoop4

	PREFETCHT0 64(SI)

	// --- Batch 1 (elements 0-3) ---

	// x = XMM(s0, s1, s2, s3)
	MOVOU (SI), X1

	// scratch = XMM(0, s0, s1, s2)
	// x += scratch                                  // yields x == XMM(s0, s0+s1, s1+s2, s2+s3)
	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1

	// scratch = XMM(0, 0, s0, s0+s1)
	// x += scratch                                  // yields x == XMM(s0, s0+s1, s0+s1+s2, s0+s1+s2+s3)
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1

	// x += offset
	PADDD X7, X1

	// y = abs(x)
	// y >>= 2 // Shift by 2*ϕ - 16.
	// y = min(y, fxAlmost65536)
	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	// Blend over the dst's prior value.
	MOVL   (DI), X0
	PSHUFB X8, X0
	MOVOU  X9, X11
	PSUBL  X2, X11
	PMULLD X11, X0
	MOVOU  X0, X11
	PSRLQ  $32, X11
	PMULULQ X10, X0
	PMULULQ X10, X11
	PSRLQ   $47, X0
	PSRLQ   $47, X11
	PSLLQ   $32, X11
	XORPS   X0, X11
	PADDD   X11, X2
	PSHUFB  X6, X2
	MOVL    X2, (DI)

	// offset = XMM(x@3, x@3, x@3, x@3)
	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	// i += 4; dst += 4; src += 16
	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI

	// --- Batch 2 (elements 4-7) ---

	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVL   (DI), X0
	PSHUFB X8, X0
	MOVOU  X9, X11
	PSUBL  X2, X11
	PMULLD X11, X0
	MOVOU  X0, X11
	PSRLQ  $32, X11
	PMULULQ X10, X0
	PMULULQ X10, X11
	PSRLQ   $47, X0
	PSRLQ   $47, X11
	PSLLQ   $32, X11
	XORPS   X0, X11
	PADDD   X11, X2
	PSHUFB  X6, X2
	MOVL    X2, (DI)

	// offset = XMM(x@3, x@3, x@3, x@3)
	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  fxAccOpOverLoop8

fxAccOpOverLoop4:
	// for i < (len(src) &^ 4)
	CMPQ R9, R12
	JAE  fxAccOpOverLoop1

	// x = XMM(s0, s1, s2, s3)
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVL   (DI), X0
	PSHUFB X8, X0
	MOVOU  X9, X11
	PSUBL  X2, X11
	PMULLD X11, X0
	MOVOU  X0, X11
	PSRLQ  $32, X11
	PMULULQ X10, X0
	PMULULQ X10, X11
	PSRLQ   $47, X0
	PSRLQ   $47, X11
	PSLLQ   $32, X11
	XORPS   X0, X11
	PADDD   X11, X2
	PSHUFB  X6, X2
	MOVL    X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  fxAccOpOverLoop4

fxAccOpOverLoop1:
	// for i < len(src)
	CMPQ R9, R11
	JAE  fxAccOpOverEnd

	// x = src[i] + offset
	MOVL  (SI), X1
	PADDD X7, X1

	// y = abs(x)
	// y >>= 2 // Shift by 2*ϕ - 16.
	// y = min(y, fxAlmost65536)
	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	// Blend over the dst's prior value.
	MOVBLZX (DI), R12
	IMULL   $0x101, R12
	MOVL    X2, R13
	MOVL    $0xffff, AX
	SUBL    R13, AX
	MULL    R12             // MULL's implicit arg is AX, and the result is stored in DX:AX.
	MOVL    $0x80008001, BX // Divide by 0xffff is to first multiply by a magic constant...
	MULL    BX              // MULL's implicit arg is AX, and the result is stored in DX:AX.
	SHRL    $15, DX         // ...and then shift by another magic constant (47 - 32 = 15).
	ADDL    DX, R13
	SHRL    $8, R13
	MOVB    R13, (DI)

	// offset = x
	MOVOU X1, X7

	// i += 1
	// dst = dst[1:]
	// src = src[1:]
	ADDQ $1, R9
	ADDQ $1, DI
	ADDQ $4, SI
	JMP  fxAccOpOverLoop1

fxAccOpOverEnd:
	RET

// ----------------------------------------------------------------------------

// func fixedAccumulateOpSrcSIMD(dst []uint8, src []uint32)
//
// XMM registers. Variable names are per
// https://github.com/google/font-rs/blob/master/src/accumulate.c
//
//	xmm0	scratch
//	xmm1	x
//	xmm2	y, z
//	xmm3	-
//	xmm4	-
//	xmm5	fxAlmost65536
//	xmm6	gather
//	xmm7	offset
//	xmm8	-
//	xmm9	-
//	xmm10	-
TEXT ·fixedAccumulateOpSrcSIMD(SB), NOSPLIT, $0-48

	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), BX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), R10

	// Sanity check that len(dst) >= len(src).
	CMPQ BX, R10
	JLT  fxAccOpSrcEnd

	MOVQ R10, R11
	MOVQ R10, R12
	ANDQ $-8, R10
	ANDQ $-4, R12

	MOVOU fxAlmost65536<>(SB), X5
	MOVOU gather<>(SB), X6

	XORPS X7, X7
	MOVQ  $0, R9

fxAccOpSrcLoop8:
	CMPQ R9, R10
	JAE  fxAccOpSrcLoop4

	PREFETCHT0 64(SI)

	// --- Batch 1 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	PSHUFB X6, X2
	MOVL   X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI

	// --- Batch 2 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	PSHUFB X6, X2
	MOVL   X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  fxAccOpSrcLoop8

fxAccOpSrcLoop4:
	CMPQ R9, R12
	JAE  fxAccOpSrcLoop1

	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	PSHUFB X6, X2
	MOVL   X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  fxAccOpSrcLoop4

fxAccOpSrcLoop1:
	CMPQ R9, R11
	JAE  fxAccOpSrcEnd

	MOVL  (SI), X1
	PADDD X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVL X2, BX
	SHRL $8, BX
	MOVB BX, (DI)

	MOVOU X1, X7

	ADDQ $1, R9
	ADDQ $1, DI
	ADDQ $4, SI
	JMP  fxAccOpSrcLoop1

fxAccOpSrcEnd:
	RET

// ----------------------------------------------------------------------------

// func fixedAccumulateMaskSIMD(buf []uint32)
//
// XMM registers. Variable names are per
// https://github.com/google/font-rs/blob/master/src/accumulate.c
//
//	xmm0	scratch
//	xmm1	x
//	xmm2	y, z
//	xmm3	-
//	xmm4	-
//	xmm5	fxAlmost65536
//	xmm6	-
//	xmm7	offset
//	xmm8	-
//	xmm9	-
//	xmm10	-
TEXT ·fixedAccumulateMaskSIMD(SB), NOSPLIT, $0-24

	MOVQ buf_base+0(FP), DI
	MOVQ buf_len+8(FP), BX
	MOVQ buf_base+0(FP), SI
	MOVQ buf_len+8(FP), R10

	MOVQ R10, R11
	MOVQ R10, R12
	ANDQ $-8, R10
	ANDQ $-4, R12

	MOVOU fxAlmost65536<>(SB), X5

	XORPS X7, X7
	MOVQ  $0, R9

fxAccMaskLoop8:
	CMPQ R9, R10
	JAE  fxAccMaskLoop4

	PREFETCHT0 64(SI)

	// --- Batch 1 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVOU X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $16, DI
	ADDQ $16, SI

	// --- Batch 2 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVOU X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $16, DI
	ADDQ $16, SI
	JMP  fxAccMaskLoop8

fxAccMaskLoop4:
	CMPQ R9, R12
	JAE  fxAccMaskLoop1

	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	PADDD X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	PADDD  X0, X1
	PADDD  X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVOU X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $16, DI
	ADDQ $16, SI
	JMP  fxAccMaskLoop4

fxAccMaskLoop1:
	CMPQ R9, R11
	JAE  fxAccMaskEnd

	MOVL  (SI), X1
	PADDD X7, X1

	PABSD  X1, X2
	PSRLL  $2, X2
	PMINUD X5, X2

	MOVL X2, (DI)

	MOVOU X1, X7

	ADDQ $1, R9
	ADDQ $4, DI
	ADDQ $4, SI
	JMP  fxAccMaskLoop1

fxAccMaskEnd:
	RET

// ----------------------------------------------------------------------------

// func floatingAccumulateOpOverSIMD(dst []uint8, src []float32)
//
// XMM registers. Variable names are per
// https://github.com/google/font-rs/blob/master/src/accumulate.c
//
//	xmm0	scratch
//	xmm1	x
//	xmm2	y, z
//	xmm3	flSignMask
//	xmm4	flOne
//	xmm5	flAlmost65536
//	xmm6	gather
//	xmm7	offset
//	xmm8	scatterAndMulBy0x101
//	xmm9	fxAlmost65536
//	xmm10	inverseFFFF
TEXT ·floatingAccumulateOpOverSIMD(SB), NOSPLIT, $8-48

	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), BX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), R10

	// Sanity check that len(dst) >= len(src).
	CMPQ BX, R10
	JLT  flAccOpOverEnd

	MOVQ R10, R11
	MOVQ R10, R12
	ANDQ $-8, R10
	ANDQ $-4, R12

	// Prepare to set MXCSR bits 13 and 14, so that the CVTPS2PL below is
	// "Round To Zero".
	STMXCSR mxcsrOrig-8(SP)
	MOVL    mxcsrOrig-8(SP), AX
	ORL     $0x6000, AX
	MOVL    AX, mxcsrNew-4(SP)

	MOVOU flSignMask<>(SB), X3
	MOVOU flOne<>(SB), X4
	MOVOU flAlmost65536<>(SB), X5

	MOVOU gather<>(SB), X6
	MOVOU scatterAndMulBy0x101<>(SB), X8
	MOVOU fxAlmost65536<>(SB), X9
	MOVOU inverseFFFF<>(SB), X10

	XORPS X7, X7
	MOVQ  $0, R9

flAccOpOverLoop8:
	CMPQ R9, R10
	JAE  flAccOpOverLoop4

	PREFETCHT0 64(SI)

	// --- Batch 1 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVL   (DI), X0
	PSHUFB X8, X0
	MOVOU  X9, X11
	PSUBL  X2, X11
	PMULLD X11, X0
	MOVOU  X0, X11
	PSRLQ  $32, X11
	PMULULQ X10, X0
	PMULULQ X10, X11
	PSRLQ   $47, X0
	PSRLQ   $47, X11
	PSLLQ   $32, X11
	XORPS   X0, X11
	PADDD   X11, X2
	PSHUFB  X6, X2
	MOVL    X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI

	// --- Batch 2 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVL   (DI), X0
	PSHUFB X8, X0
	MOVOU  X9, X11
	PSUBL  X2, X11
	PMULLD X11, X0
	MOVOU  X0, X11
	PSRLQ  $32, X11
	PMULULQ X10, X0
	PMULULQ X10, X11
	PSRLQ   $47, X0
	PSRLQ   $47, X11
	PSLLQ   $32, X11
	XORPS   X0, X11
	PADDD   X11, X2
	PSHUFB  X6, X2
	MOVL    X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  flAccOpOverLoop8

flAccOpOverLoop4:
	CMPQ R9, R12
	JAE  flAccOpOverLoop1

	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVL   (DI), X0
	PSHUFB X8, X0
	MOVOU  X9, X11
	PSUBL  X2, X11
	PMULLD X11, X0
	MOVOU  X0, X11
	PSRLQ  $32, X11
	PMULULQ X10, X0
	PMULULQ X10, X11
	PSRLQ   $47, X0
	PSRLQ   $47, X11
	PSLLQ   $32, X11
	XORPS   X0, X11
	PADDD   X11, X2
	PSHUFB  X6, X2
	MOVL    X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  flAccOpOverLoop4

flAccOpOverLoop1:
	CMPQ R9, R11
	JAE  flAccOpOverEnd

	MOVL  (SI), X1
	ADDPS X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVBLZX (DI), R12
	IMULL   $0x101, R12
	MOVL    X2, R13
	MOVL    $0xffff, AX
	SUBL    R13, AX
	MULL    R12
	MOVL    $0x80008001, BX
	MULL    BX
	SHRL    $15, DX
	ADDL    DX, R13
	SHRL    $8, R13
	MOVB    R13, (DI)

	MOVOU X1, X7

	ADDQ $1, R9
	ADDQ $1, DI
	ADDQ $4, SI
	JMP  flAccOpOverLoop1

flAccOpOverEnd:
	RET

// ----------------------------------------------------------------------------

// func floatingAccumulateOpSrcSIMD(dst []uint8, src []float32)
//
// XMM registers. Variable names are per
// https://github.com/google/font-rs/blob/master/src/accumulate.c
//
//	xmm0	scratch
//	xmm1	x
//	xmm2	y, z
//	xmm3	flSignMask
//	xmm4	flOne
//	xmm5	flAlmost65536
//	xmm6	gather
//	xmm7	offset
//	xmm8	-
//	xmm9	-
//	xmm10	-
TEXT ·floatingAccumulateOpSrcSIMD(SB), NOSPLIT, $8-48

	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), BX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), R10

	// Sanity check that len(dst) >= len(src).
	CMPQ BX, R10
	JLT  flAccOpSrcEnd

	MOVQ R10, R11
	MOVQ R10, R12
	ANDQ $-8, R10
	ANDQ $-4, R12

	STMXCSR mxcsrOrig-8(SP)
	MOVL    mxcsrOrig-8(SP), AX
	ORL     $0x6000, AX
	MOVL    AX, mxcsrNew-4(SP)

	MOVOU flSignMask<>(SB), X3
	MOVOU flOne<>(SB), X4
	MOVOU flAlmost65536<>(SB), X5
	MOVOU gather<>(SB), X6

	XORPS X7, X7
	MOVQ  $0, R9

flAccOpSrcLoop8:
	CMPQ R9, R10
	JAE  flAccOpSrcLoop4

	PREFETCHT0 64(SI)

	// --- Batch 1 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	PSHUFB X6, X2
	MOVL   X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI

	// --- Batch 2 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	PSHUFB X6, X2
	MOVL   X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  flAccOpSrcLoop8

flAccOpSrcLoop4:
	CMPQ R9, R12
	JAE  flAccOpSrcLoop1

	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	PSHUFB X6, X2
	MOVL   X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $4, DI
	ADDQ $16, SI
	JMP  flAccOpSrcLoop4

flAccOpSrcLoop1:
	CMPQ R9, R11
	JAE  flAccOpSrcEnd

	MOVL  (SI), X1
	ADDPS X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVL X2, BX
	SHRL $8, BX
	MOVB BX, (DI)

	MOVOU X1, X7

	ADDQ $1, R9
	ADDQ $1, DI
	ADDQ $4, SI
	JMP  flAccOpSrcLoop1

flAccOpSrcEnd:
	RET

// ----------------------------------------------------------------------------

// func floatingAccumulateMaskSIMD(dst []uint32, src []float32)
//
// XMM registers. Variable names are per
// https://github.com/google/font-rs/blob/master/src/accumulate.c
//
//	xmm0	scratch
//	xmm1	x
//	xmm2	y, z
//	xmm3	flSignMask
//	xmm4	flOne
//	xmm5	flAlmost65536
//	xmm6	-
//	xmm7	offset
//	xmm8	-
//	xmm9	-
//	xmm10	-
TEXT ·floatingAccumulateMaskSIMD(SB), NOSPLIT, $8-48

	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), BX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), R10

	// Sanity check that len(dst) >= len(src).
	CMPQ BX, R10
	JLT  flAccMaskEnd

	MOVQ R10, R11
	MOVQ R10, R12
	ANDQ $-8, R10
	ANDQ $-4, R12

	STMXCSR mxcsrOrig-8(SP)
	MOVL    mxcsrOrig-8(SP), AX
	ORL     $0x6000, AX
	MOVL    AX, mxcsrNew-4(SP)

	MOVOU flSignMask<>(SB), X3
	MOVOU flOne<>(SB), X4
	MOVOU flAlmost65536<>(SB), X5

	XORPS X7, X7
	MOVQ  $0, R9

flAccMaskLoop8:
	CMPQ R9, R10
	JAE  flAccMaskLoop4

	PREFETCHT0 64(SI)

	// --- Batch 1 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVOU X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $16, DI
	ADDQ $16, SI

	// --- Batch 2 ---
	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVOU X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $16, DI
	ADDQ $16, SI
	JMP  flAccMaskLoop8

flAccMaskLoop4:
	CMPQ R9, R12
	JAE  flAccMaskLoop1

	MOVOU (SI), X1

	MOVOU X1, X0
	PSLLO $4, X0
	ADDPS X0, X1
	XORPS  X0, X0
	SHUFPS $0x40, X1, X0
	ADDPS  X0, X1
	ADDPS  X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVOU X2, (DI)

	MOVOU  X1, X7
	SHUFPS $0xff, X1, X7

	ADDQ $4, R9
	ADDQ $16, DI
	ADDQ $16, SI
	JMP  flAccMaskLoop4

flAccMaskLoop1:
	CMPQ R9, R11
	JAE  flAccMaskEnd

	MOVL  (SI), X1
	ADDPS X7, X1

	MOVOU X3, X2
	ANDPS X1, X2
	MINPS X4, X2
	MULPS X5, X2

	LDMXCSR  mxcsrNew-4(SP)
	CVTPS2PL X2, X2
	LDMXCSR  mxcsrOrig-8(SP)

	MOVL X2, (DI)

	MOVOU X1, X7

	ADDQ $1, R9
	ADDQ $4, DI
	ADDQ $4, SI
	JMP  flAccMaskLoop1

flAccMaskEnd:
	RET
